"""initialization

Revision ID: b93406014a0e
Revises: 
Create Date: 2024-01-25 20:10:18.916771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93406014a0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_auth'
    )
    op.create_index(op.f('ix_fastapi_auth_role_name'), 'role', ['name'], unique=True, schema='fastapi_auth')
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=220), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_auth'
    )
    op.create_index(op.f('ix_fastapi_auth_user_email'), 'user', ['email'], unique=True, schema='fastapi_auth')
    op.create_index(op.f('ix_fastapi_auth_user_role_id'), 'user', ['role_id'], unique=False, schema='fastapi_auth')
    op.create_index(op.f('ix_fastapi_auth_user_username'), 'user', ['username'], unique=True, schema='fastapi_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_auth_user_username'), table_name='user', schema='fastapi_auth')
    op.drop_index(op.f('ix_fastapi_auth_user_role_id'), table_name='user', schema='fastapi_auth')
    op.drop_index(op.f('ix_fastapi_auth_user_email'), table_name='user', schema='fastapi_auth')
    op.drop_table('user', schema='fastapi_auth')
    op.drop_index(op.f('ix_fastapi_auth_role_name'), table_name='role', schema='fastapi_auth')
    op.drop_table('role', schema='fastapi_auth')
    # ### end Alembic commands ###
